# Leaflow 部署清单 - FastAPI 后端
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-backend
  labels:
    app: contract-backend
    version: v1.0.0
spec:
  replicas: 3  # 高可用配置
  selector:
    matchLabels:
      app: contract-backend
  template:
    metadata:
      labels:
        app: contract-backend
    spec:
      containers:
      - name: fastapi
        image: your-registry/contract-backend:latest  # 替换为你的镜像地址
        ports:
        - containerPort: 8000
          name: http
        
        # 环境变量
        env:
        - name: APP_ENV
          value: "production"
        - name: DEBUG
          value: "false"
        
        # 数据库连接（从 Secret 读取）
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: contract-secrets
              key: database-url
        
        # MinIO 配置（从 Secret 读取）
        - name: MINIO_ENDPOINT
          value: "minio-service:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: contract-secrets
              key: minio-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: contract-secrets
              key: minio-secret-key
        - name: MINIO_BUCKET
          value: "contract-storage"
        - name: MINIO_SECURE
          value: "false"
        
        # Redis 配置
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        
        # Gemini API（从 Secret 读取）
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: contract-secrets
              key: gemini-api-key
        - name: GEMINI_MODEL
          value: "gemini-2.0-flash-exp"
        
        # JWT 配置（从 Secret 读取）
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: contract-secrets
              key: jwt-secret
        
        # CORS 配置
        - name: CORS_ORIGINS
          value: "https://your-app.leaflow.dev"
        
        # 资源限制
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "4Gi"
            cpu: "4000m"
        
        # 健康检查
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
# Service 配置
apiVersion: v1
kind: Service
metadata:
  name: contract-backend-service
  labels:
    app: contract-backend
spec:
  selector:
    app: contract-backend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP

---
# Secret 配置（需要手动创建）
# kubectl create secret generic contract-secrets \
#   --from-literal=database-url='postgresql://...' \
#   --from-literal=minio-access-key='...' \
#   --from-literal=minio-secret-key='...' \
#   --from-literal=gemini-api-key='...' \
#   --from-literal=jwt-secret='...'
